name: Trigger build
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Number of the PR which triggered this action"
        required: true
      creator_username:
        description: "Username of the PR creator"
        required: true
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          repo: ${{ secrets.GITHUBBRASIL_NWO }}
          workflow: Trigger build when public PR is merged
          token: ${{ secrets.PAT }}
          inputs: '{"pr_number": "${{ github.event.inputs.pr_number }}", "creator_username": "${{ github.event.inputs.creator_username }}" }'
