name: Trigger build
on:
  pull_request:
    types:
      - closed
    paths:
      - "website/**"
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ secrets.ORG_NAME }}
          repo: ${{ secrets.REPO_NAME }}
          workflow_file_name: trigger_build_when_public_pr_merged.yml
          github_token: ${{ secrets.PAT }}
          wait_workflow: false
          client_payload: '{"pr_number": "${{ github.event.number }}", "creator_username": "${{ github.event.pull_request.user.login  }}" }'
